# Generated by Django 5.0.4 on 2024-04-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_medicaldata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldata',
            old_name='rg',
            new_name='register_geral',
        ),
    ]
